### ISSUE TITLE
Custom Block Render method loses reference to Context Provider (MUI / React Query)

### ISSUE THREAD

**Issue by natti-tamnoon** [TypeCellOS/BlockNote#581]
**Describe the bug**
Custom Blocks lose reference to context providers inside the custom block `render` method.

**To Reproduce**
set up a project with any type of context provider (react query, material ui), and trying to use the context provider hooks (`useTheme` / `useQuery`) inside the render will fail. 

A workaround solution found is to wrap the components again in the context provider. This is not ideal solution as it requires the custom blocks to be written in a way where everything can be additionally wrapped by the context providers.

It seems like the render for custom blocks removes the component from the main tree of components.

**Comment by YousefED** [comment]
Hi!

This should not be the case (it should be working). Which version of BlockNote are you using? Could you provide a codesandbox or similar?

**Comment by natti-tamnoon** [comment]
> Hi!
> 
> This should not be the case (it should be working). Which version of BlockNote are you using? Could you provide a codesandbox or similar?

fair point. We're currently using `0.10.1` where the issue is seen. Testing on latest `0.11.2` in sandboxed mini project with custom block using mui theme to set font color inside the render, I don't see the issue persisting there.

We'll look into upgrade option. I'll close this. Thanks for quick reply :)

**Comment by YousefED** [comment]
Nice! Curious ti hear what kind of project you're using BlockNote for btw @natti-tamnoon

**Comment by natti-tamnoon** [comment]
> Nice! Curious ti hear what kind of project you're using BlockNote for btw @natti-tamnoon 

@YousefED it's a cybersecurity remediation platform. Editor is to add info how to deal with target alerts.
https://tamnoon.io/

**Comment by YousefED** [comment]
@natti-tamnoon Great, thanks for sharing! Always nice to hear about use-cases / success stories!
